source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!

target 'PPEventRegistryTest' do
  pod 'SwiftyJSON', :git => 'https://github.com/ratkins/SwiftyJSON.git', :branch => 'swift3'
  pod 'PPEventRegistryAPI', :path => '..'
end

# [Xcode 8 beta 2]: CopySwiftLibs for Pods framework fails with Mach-O header error #5598
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
