source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'PPEventRegistryTest' do
  platform :ios, '10.0'
  pod 'PPEventRegistryAPI', :path => '..'
end

target 'PPEventRegistryTest tvOS' do
    platform :tvos, '10.0'
    pod 'PPEventRegistryAPI', :path => '..'
end

target 'PPEventRegistryTest watchOS' do
    platform :watchos, '3.0'
    pod 'PPEventRegistryAPI', :path => '..'
end

target 'PPEventRegistryTest watchOS Extension' do
    platform :watchos, '3.0'
    pod 'PPEventRegistryAPI', :path => '..'
end

target 'PPEventRegistryTest macOS' do
  platform :osx, '10.12'
  pod 'PPEventRegistryAPI', :path => '..'
end

# [Xcode 8 beta 2]: CopySwiftLibs for Pods framework fails with Mach-O header error #5598
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
