source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def event_registry
    pod 'PPEventRegistryAPI', :path => '..'
end

target 'PPEventRegistryTest' do
    event_registry
    platform :ios, '10.0'
end

target 'PPEventRegistryTest tvOS' do
    event_registry
    platform :tvos, '10.0'
end

target 'PPEventRegistryTest watchOS' do
    event_registry
    platform :watchos, '3.0'
end

target 'PPEventRegistryTest watchOS Extension' do
    event_registry
    platform :watchos, '3.0'
end

target 'PPEventRegistryTest macOS' do
    event_registry
    platform :osx, '10.12'
end
