source 'https://github.com/CocoaPods/Specs.git'

project 'PPEventRegistryAPI.xcodeproj'
inhibit_all_warnings!

use_frameworks!

def testing_pods
  pod 'PPEventRegistryAPI', :path => '../'
  pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-3.0'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'swift-3.0'
  pod 'OHHTTPStubs', :git => 'https://github.com/AliSoftware/OHHTTPStubs.git', :branch => 'xcode8-gm'
  pod 'OHHTTPStubs/Swift', :git => 'https://github.com/AliSoftware/OHHTTPStubs.git', :branch => 'xcode8-gm'
end

target 'WatchHost watchOS Extension' do
  # hosting target of `PPEventRegistryAPI watchOS`
  platform :watchos, '3.0'
end

abstract_target 'TargetPods' do
  target 'PPEventRegistryAPI iOS' do
    platform :ios, '10.0'
  end

  target 'PPEventRegistryAPI tvOS' do
    platform :tvos, '10.0'
  end

  target 'PPEventRegistryAPI watchOS' do
    platform :watchos, '3.0'
  end

  target 'PPEventRegistryAPI macOS' do
    platform :osx, '10.12'
  end

end

abstract_target 'TestingPods' do
  testing_pods

  target 'PPEventRegistryAPITests iOS' do
    platform :ios, '10.0'
  end

  target 'PPEventRegistryAPITests tvOS' do
    platform :tvos, '10.0'
  end

  target 'PPEventRegistryAPITests macOS' do
    platform :osx, '10.12'
  end

end
